name: "SmartHop Backfill"
version: "0.1.5"
slug: "backfill"
description: "Automatic backfill of Home Assistant history to InfluxDB."
url: "https://github.com/adminsmarthop/smarthop-backfill"

startup: application
boot: auto
init: false

arch:
  - amd64
  - aarch64

homeassistant_api: true

options:
  influx_url: null
  influx_org: null
  influx_bucket: null
  influx_token: null
  site: null
  days: 30
  interval_days: 7
  entities: []

schema:
  influx_url: url
  influx_org: str
  influx_bucket: str
  influx_token: password
  site: str
  days: int(1,90)
  interval_days: int(1,30)
  entities:
    - str
